name: Flask CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-flask:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask netcat

    - name: Run Flask app and test endpoints
      run: |
        # Start Flask in background
        python sum.py &
        FLASK_PID=$!

        # Wait until Flask is ready (max 15 seconds)
        for i in {1..15}; do
          if nc -z 127.0.0.1 5000; then
            echo "Flask is ready!"
            break
          fi
          echo "Waiting for Flask..."
          sleep 1
        done

        # Test root endpoint
        echo "Testing root endpoint..."
        curl -s http://127.0.0.1:5000/

        # Test addition endpoint
        echo "Testing addition endpoint..."
        curl -s "http://127.0.0.1:5000/add?a=5&b=3"

        # Stop Flask
        kill $FLASK_PID
