name: Flask App Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Flask app and test endpoints
      run: |
        python sum.py &
        sleep 5
        echo "Testing root endpoint..."
        curl "http://127.0.0.1:5000/"
        echo "Testing addition endpoint..."
        curl "http://127.0.0.1:5000/add?a=5&b=3"


